"""
slug_validation_report.py — Live slug validation results for TASK-15.

Generated by running live HTTP requests against each store on 2026-05-27.
NOT imported by the application.

KEY FINDINGS:
- None of the 5 stores uses the standard /product-category/{slug}/ pattern as initially assumed.
- WooCommerceScraper._build_category_url hardcodes /product-category/{slug}/ which
  is INCOMPATIBLE with 4 of the 5 stores.
- Phase-2 work required: add url_template support to WooCommerceScraper and update
  selectors per-store.

STORE-BY-STORE SUMMARY:
  techzilla    -> Water-cooling-ONLY specialty store.  NO CPUs/GPUs/RAM/etc.
                  Correct slugs: kits-de-enfriamiento, componentes-wc, herramientas-custom-water-cooling
                  Config slugs were wrong best-guesses; all 9 categories NOT AVAILABLE.
  crtechstore  -> Nested path: /categoria-producto/tecnologia/componentes/{slug}/
                  WoodMart theme. Products in div.product-grid-item, NOT li.product.
  igamingcr    -> Custom taxonomy: /Categoria/componentes/{slug}/ (capital C).
                  li.product exists but content is JS-rendered (lazy-loaded).
                  WP REST API confirms product counts: gpu=18, cpu=22, tm=24, etc.
  intelec      -> Flat slug: https://www.intelec.co.cr/{slug}/ (redirect from intelec.co.cr).
                  WoodMart theme. Products in .product-grid-item, NOT li.product.
                  All category pages return HTTP 200 with 20 products each.
  extremetechcr -> Body nearly empty without JS execution.
                   Cannot be scraped with requests/cloudscraper. Phase-2: Playwright required.
"""

SLUG_VALIDATION_REPORT: dict = {

    # ------------------------------------------------------------------
    # Techzilla -- water-cooling specialty store, NOT a general PC store
    # ------------------------------------------------------------------
    "techzilla": {
        "store_url": "https://techzilla.cr",
        "url_pattern": "/product-category/{slug}/",
        "product_selector": "li.product",
        "products_verified": False,
        "note": (
            "Techzilla is a WATER COOLING SPECIALTY store (EKWB, Alphacool). "
            "It does NOT stock CPUs, GPUs, RAM, Monitors, Cases, or PSUs. "
            "All Phase-1 category slugs were incorrect best-guesses. "
            "Store should be REMOVED from Phase-1 comparison or repurposed "
            "as a water-cooling category store."
        ),
        "categories": {
            "CPUs":             {"original": "procesadores",      "validated": None,  "status": "NOT_AVAILABLE", "products": 0},
            "GPUs":             {"original": "tarjetas-de-video", "validated": None,  "status": "NOT_AVAILABLE", "products": 0},
            "Placas madre":     {"original": "tarjetas-madre",    "validated": None,  "status": "NOT_AVAILABLE", "products": 0},
            "RAM":              {"original": "memorias-ram",      "validated": None,  "status": "NOT_AVAILABLE", "products": 0},
            "Disipadores":      {"original": "disipadores",       "validated": "kits-de-enfriamiento",
                                 "status": "REDIRECTED", "products": 0,
                                 "note": "Sells WC kits, not standard CPU/case coolers"},
            "Almacenamiento":   {"original": "almacenamiento",    "validated": None,  "status": "NOT_AVAILABLE", "products": 0},
            "Fuentes de poder": {"original": "fuentes-de-poder",  "validated": None,  "status": "NOT_AVAILABLE", "products": 0},
            "Cases":            {"original": "cases",             "validated": None,  "status": "NOT_AVAILABLE", "products": 0},
            "Monitores":        {"original": "monitores",         "validated": None,  "status": "NOT_AVAILABLE", "products": 0},
        },
        "real_categories": [
            "kits-de-enfriamiento",
            "componentes-wc",
            "herramientas-custom-water-cooling",
            "otras-categorias",
        ],
    },

    # ------------------------------------------------------------------
    # CRTechStore -- WoodMart theme, nested /categoria-producto/ paths
    # ------------------------------------------------------------------
    "crtechstore": {
        "store_url": "https://crtechstore.com",
        "url_pattern": "/categoria-producto/tecnologia/componentes/{slug}/",
        "product_selector": "div.product-grid-item",  # NOT li.product
        "products_verified": True,
        "note": (
            "Uses /categoria-producto/ (Spanish WC localisation) with nested path "
            "'tecnologia/componentes/'. WoodMart theme -- product cards are "
            "div.product-grid-item, NOT li.product. WooCommerceScraper needs "
            "selector override and url_template support."
        ),
        "categories": {
            "CPUs":             {"original": "procesadores",      "validated": "tecnologia/componentes/procesadores",            "status": "VALID_CORRECTED_PATH",   "products": "20+"},
            "GPUs":             {"original": "tarjetas-graficas", "validated": "tecnologia/componentes/tarjetas-de-video",       "status": "VALID_CORRECTED_PATH",   "products": "59+"},
            "Placas madre":     {"original": "placas-madre",      "validated": "tecnologia/componentes/tarjetas-madre",          "status": "VALID_CORRECTED_PATH",   "products": "20+"},
            "RAM":              {"original": "memoria-ram",       "validated": "tecnologia/componentes/memoria-ram",             "status": "VALID_SAME_SLUG",        "products": "20+"},
            "Disipadores":      {"original": "refrigeracion",     "validated": "tecnologia/componentes/sistemas-de-enfriamiento","status": "VALID_CORRECTED_PATH",   "products": "20+"},
            "Almacenamiento":   {"original": "almacenamiento",    "validated": "tecnologia/componentes/almacenamiento",          "status": "VALID_SAME_SLUG",        "products": "20+"},
            "Fuentes de poder": {"original": "fuentes-de-poder",  "validated": "tecnologia/componentes/fuentes-de-poder",        "status": "VALID_SAME_SLUG",        "products": "20+"},
            "Cases":            {"original": "gabinetes",         "validated": "tecnologia/componentes/cases",                   "status": "VALID_CORRECTED_PATH",   "products": "59+"},
            "Monitores":        {"original": "monitores",         "validated": "tecnologia/perifericos-y-accesorios/monitores",  "status": "VALID_CORRECTED_PATH",   "products": "20+"},
        },
    },

    # ------------------------------------------------------------------
    # iGaming CR -- custom /Categoria/ taxonomy, JS-rendered content
    # ------------------------------------------------------------------
    "igamingcr": {
        "store_url": "https://igamingcr.com",
        "url_pattern": "/Categoria/{slug}/",  # capital C, custom WP taxonomy
        "product_selector": "li.product",
        "products_verified": True,
        "note": (
            "Uses capital-C /Categoria/ custom WP taxonomy (not standard WC /product-category/). "
            "li.product elements present in HTML but content is lazy-loaded via JS. "
            "WP REST API (wp-json/wp/v2/product) works without auth. "
            "WooCommerceScraper._build_category_url must be overridden via url_template "
            "OR category_map slugs must include the full relative path."
        ),
        "categories": {
            "CPUs":             {"original": "procesadores",    "validated": "componentes/cpu",            "status": "VALID_CORRECTED_PATH", "products": 22,  "wp_cat_slug": "cpu"},
            "GPUs":             {"original": "tarjetas-de-video", "validated": "componentes/gpu",          "status": "VALID_CORRECTED_PATH", "products": 18,  "wp_cat_slug": "gpu"},
            "Placas madre":     {"original": "motherboards",   "validated": "componentes/tm",             "status": "VALID_CORRECTED_PATH", "products": 24,  "wp_cat_slug": "tm"},
            "RAM":              {"original": "memoria-ram",    "validated": "componentes/mem",            "status": "VALID_CORRECTED_PATH", "products": 21,  "wp_cat_slug": "mem"},
            "Disipadores":      {"original": "cooling",        "validated": "componentes/cooler",         "status": "VALID_CORRECTED_PATH", "products": 65,  "wp_cat_slug": "cooler"},
            "Almacenamiento":   {"original": "almacenamiento", "validated": "componentes/almacenamiento", "status": "VALID_SAME_SLUG",      "products": 44,  "wp_cat_slug": "almacenamiento"},
            "Fuentes de poder": {"original": "power-supply",   "validated": "componentes/ps",             "status": "VALID_CORRECTED_PATH", "products": 16,  "wp_cat_slug": "ps"},
            "Cases":            {"original": "cases",          "validated": "componentes/case",           "status": "VALID_CORRECTED_SLUG", "products": 43,  "wp_cat_slug": "case"},
            "Monitores":        {"original": "monitores",      "validated": "perifericos/monit",          "status": "VALID_CORRECTED_PATH", "products": 35,  "wp_cat_slug": "monit"},
        },
        "base_url_note": "url_template must be '{base}/Categoria/{slug}/'",
    },

    # ------------------------------------------------------------------
    # Intelec -- flat slug paths, WoodMart theme
    # ------------------------------------------------------------------
    "intelec": {
        "store_url": "https://www.intelec.co.cr",
        "url_pattern": "/{slug}/",  # flat -- no /product-category/ prefix
        "product_selector": "div.product-grid-item",  # WoodMart, NOT li.product
        "products_verified": True,
        "note": (
            "intelec.co.cr redirects to www.intelec.co.cr. "
            "Uses FLAT slug paths (/{slug}/), no /product-category/ prefix. "
            "WoodMart theme -- product cards are div.product-grid-item. "
            "url_template must be '{base}/{slug}/' and selector overridden. "
            "All 9 categories return HTTP 200 with ~20 products per page."
        ),
        "categories": {
            "CPUs":             {"original": "procesadores",   "validated": "procesadores",                    "status": "VALID_WRONG_TEMPLATE", "products": 20},
            "GPUs":             {"original": "tarjetas-de-video", "validated": "tarjetas-de-video",            "status": "VALID_WRONG_TEMPLATE", "products": 20},
            "Placas madre":     {"original": "tarjetas-madre", "validated": "tarjeta-madre",                   "status": "VALID_CORRECTED_SLUG", "products": 20},
            "RAM":              {"original": "memorias-ram",   "validated": "memorias-para-pc",                "status": "VALID_CORRECTED_SLUG", "products": 20},
            "Disipadores":      {"original": "enfriamiento",   "validated": "enfriamientos",                   "status": "VALID_CORRECTED_SLUG", "products": 20},
            "Almacenamiento":   {"original": "almacenamiento", "validated": "discos-duros-ssd-y-almacenamiento", "status": "VALID_CORRECTED_SLUG", "products": 20},
            "Fuentes de poder": {"original": "fuentes",        "validated": "fuentes-de-poder",                "status": "VALID_CORRECTED_SLUG", "products": 20},
            "Cases":            {"original": "cases",          "validated": "cases",                           "status": "VALID_WRONG_TEMPLATE", "products": 20},
            "Monitores":        {"original": "monitores",      "validated": "monitores",                       "status": "VALID_WRONG_TEMPLATE", "products": 20},
        },
        "base_url_note": "Use base_url='https://www.intelec.co.cr'; url_template='{base}/{slug}/'",
    },

    # ------------------------------------------------------------------
    # ExtremeTech CR -- JS-rendered (requires Playwright/Selenium)
    # ------------------------------------------------------------------
    "extremetechcr": {
        "store_url": "https://extremetechcr.com",
        "url_pattern": "/product-category/{slug}/",  # URL pattern correct but content is JS-rendered
        "product_selector": "li.product",
        "products_verified": False,
        "note": (
            "Static HTML body is nearly empty (live chat widget + inline scripts only). "
            "No navigation links visible without JS. "
            "Cannot be scraped with requests or cloudscraper alone. "
            "Phase-2: requires Playwright or Selenium for headless browser rendering. "
            "Disable in Phase-1 (set enabled=False)."
        ),
        "categories": {
            "CPUs":             {"original": "procesadores",    "validated": "procesadores",    "status": "URL_OK_JS_REQUIRED", "products": 0},
            "GPUs":             {"original": "tarjetas-graficas", "validated": "tarjetas-graficas", "status": "URL_OK_JS_REQUIRED", "products": 0},
            "Placas madre":     {"original": "motherboards",   "validated": None,              "status": "URL_404_JS_REQUIRED", "products": 0},
            "RAM":              {"original": "memorias",        "validated": None,              "status": "URL_404_JS_REQUIRED", "products": 0},
            "Disipadores":      {"original": "cooling",         "validated": None,              "status": "URL_404_JS_REQUIRED", "products": 0},
            "Almacenamiento":   {"original": "almacenamiento",  "validated": "almacenamiento",  "status": "URL_OK_JS_REQUIRED", "products": 0},
            "Fuentes de poder": {"original": "fuentes-poder",   "validated": None,              "status": "URL_404_JS_REQUIRED", "products": 0},
            "Cases":            {"original": "cases",           "validated": None,              "status": "URL_404_JS_REQUIRED", "products": 0},
            "Monitores":        {"original": "monitores",       "validated": "monitores",       "status": "URL_OK_JS_REQUIRED", "products": 0},
        },
    },
}

# ------------------------------------------------------------------
# Recommended config.py changes
# ------------------------------------------------------------------

RECOMMENDED_CHANGES = {
    "techzilla": (
        "REMOVE or repurpose as water-cooling store. "
        "Replace with a real PC component store in Phase-2."
    ),
    "crtechstore": [
        "Add url_template = '{base}/categoria-producto/{slug}/' to StoreConfig",
        "Fix WooCommerceScraper._build_category_url to use url_template",
        "Prepend 'tecnologia/componentes/' to component slugs",
        "Slug fix: GPUs -> tarjetas-de-video (was tarjetas-graficas)",
        "Slug fix: Placas madre -> tarjetas-madre (was placas-madre)",
        "Slug fix: Disipadores -> sistemas-de-enfriamiento (was refrigeracion)",
        "Slug fix: Cases -> cases (was gabinetes)",
        "Slug fix: Monitores -> tecnologia/perifericos-y-accesorios/monitores",
        "Selector fix: product_card -> 'div.product-grid-item'",
    ],
    "igamingcr": [
        "Change url_template = '{base}/Categoria/{slug}/'",
        "Fix WooCommerceScraper._build_category_url to use url_template",
        "Update all slugs to short WP taxonomy slugs with 'componentes/' prefix",
        "Selector fix: JS-rendered content; consider WP REST API approach",
    ],
    "intelec": [
        "Change base_url to 'https://www.intelec.co.cr'",
        "Change url_template = '{base}/{slug}/'",
        "Fix WooCommerceScraper._build_category_url to use url_template",
        "Slug fix: Placas madre -> tarjeta-madre (was tarjetas-madre)",
        "Slug fix: RAM -> memorias-para-pc (was memorias-ram)",
        "Slug fix: Disipadores -> enfriamientos (was enfriamiento)",
        "Slug fix: Almacenamiento -> discos-duros-ssd-y-almacenamiento",
        "Slug fix: Fuentes de poder -> fuentes-de-poder (was fuentes)",
        "Selector fix: product_card -> 'div.product-grid-item'",
    ],
    "extremetechcr": [
        "Set enabled=False in Phase-1",
        "Phase-2: implement headless browser scraper (Playwright)",
    ],
}
